name: jump-validator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pyteomics
  - openpyxl
  - xlsxwriter
  - pip
  - pip:
      - dataframe_image
      - python-docx
